site_name: Palo Alto Networks Policy Orchestration with Ansible
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html


plugins:
  - mkdocstrings
  - autorefs
  - mermaid2

theme:
  name: "material"
  palette:
    primary: black
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.copy
    - content.code.select

repo_url: https://github.com/adambaumeister/ansible_panos_policy_orchestration

nav:
  - Introduction: index.md
  - User Guide:
      - Introduction: user_guide/introduction.md
      - Preset Policy: user_guide/preset_policy.md
      - New Policy Creation: user_guide/new_policy_creation.md
  - Changelog: CHANGELOG.md

extra:
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:abaumeister@paloaltonetworks.com
