---
# Creates a new policy based on the information we have gathered up to this point.

- name: Populate Defaults
  set_fact:
    source_zones: "{{ source_zones | default(['any']) }}"
    destination_zones: "{{ destination_zones | default(['any']) }}"
    tag: "{{ tag | default(default_new_policy_tag) }}"
    rule_name: "autogen_{{ ansible_date_time.epoch }}"
    source_address_name: "addr_{{ source_ip | replace('.', '_') | replace('/', '_') }}"
    destination_address_name: "addr_{{ destination_ip | replace('.', '_') | replace('/', '_') }}"
    device_group: "{{ device_group | default(default_new_policy_device_group) }}"

- name: Create the TAG if required
  paloaltonetworks.panos.panos_tag_object:
    provider:
      ip_address: "{{ provider.ip_address }}"
      username: "{{ provider.username }}"
      password: "{{ provider.password }}"
    name: "{{ tag }}"
    color: "black"
    device_group: shared

- name: Create ADDRESS object for source IP
  paloaltonetworks.panos.panos_address_object:
    provider: "{{ provider }}"
    device_group: "{{ device_group }}"
    name: "{{ source_address_name }}"
    value: "{{ source_ip }}"
    address_type: "ip-netmask"
    description: "Auto-created address object"
    state: present

- name: Create ADDRESS object for destination IP
  paloaltonetworks.panos.panos_address_object:
    provider: "{{ provider }}"
    device_group: "{{ device_group }}"
    name: "{{ destination_address_name }}"
    value: "{{ destination_ip }}"
    address_type: "ip-netmask"
    description: "Auto-created address object"
    state: present

- name: Create the SECURITY RULE
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    device_group: "{{ device_group }}"
    rule_name: "{{ rule_name }}"
    description: "Created by automation at  {{ ansible_date_time.epoch }}"
    tag_name: ["{{ tag }}"]
    source_zone: "{{ source_zones }}"
    source_ip: ["{{ source_ip }}"]
    destination_zone: "{{ destination_zones }}"
    destination_ip: ["{{ destination_ip }}"]
    application: ["{{ application }}"]
    action: "allow"

- name: Update facts
  set_fact:
    policy_created: "{{ rule_name }}"
