---
# Deploy policy to the 'lab' environment

- hosts: lab
  connection: local
  name: Deploy policy to the Lab Environment
  vars:
    provider:
      ip_address: "{{ ansible_host }}"
      username: "{{ lookup('env', 'PAN_USERNAME') }}"
      password: "{{ lookup('env', 'PAN_PASSWORD') }}"
    policy_match: false

  tasks:
    - name: Test against Webserver outbound policy
      ansible.builtin.include_tasks:
        file: add_policy.yml
