---
# Panorama Connectivity Test Playbook
#
# This playbook validates basic connectivity to Panorama devices.
# It performs simple authentication and status checks without making any changes.
#
# Usage:
#   export PAN_PASSWORD="your_device_password"
#   ansible-playbook -i inventory.yml playbooks/testing/connectivity.yml

- hosts: lab
  gather_facts: false
  connection: local

  tasks:
    - name: Test Panorama connectivity and authentication
      paloaltonetworks.panos.panos_op:
        provider:
          ip_address: "{{ ansible_host }}"
          username: "{{ lookup('env', 'PAN_USERNAME') }}"
          password: "{{ lookup('env', 'PAN_PASSWORD') }}"
        cmd: "show system info"
      register: system_info
      failed_when: false

    - name: Display connectivity test results
      debug:
        msg: |
          Panorama: {{ ansible_host }}
          Status: {{ 'SUCCESS' if system_info.stdout is defined else 'FAILED' }}
          {% if system_info.stdout is defined %}
          Connected successfully to Panorama
          {% else %}
          Connection failed: {{ system_info.msg | default('Unknown error') }}
          {% endif %}

    - name: Fail if connectivity test failed
      fail:
        msg: "Failed to connect to Panorama at {{ ansible_host }}"
      when: system_info.stdout is not defined