---
- hosts: lab
  connection: local
  gather_facts: false
  name: Test the Lookup Policy playbook

  vars:
    provider:
      ip_address: "{{ ansible_host }}"
      username: "{{ lookup('env', 'PAN_USERNAME') }}"
      password: "{{ lookup('env', 'PAN_PASSWORD') }}"
    destination_port: 22

  tasks:
    - name: Test lookup policy tasks
      ansible.builtin.include_tasks:
        file: ../orchestrator/new/lookup_policy.yml

    - name: Print the results
      debug:
        msg: '{{ security_policy_match_result }}'
