---
# Tasks file which creates a single address as an address object in the given device group, identified by the variables
# {{ device_group }} and {{ _address_group }}

- name: Determine the object name
  ansible.builtin.set_fact:
    created_object_name: "addr_{{ _address | replace('.', '_') | replace('/', '_') }}"

- name: Create ADDRESS object
  paloaltonetworks.panos.panos_address_object:
    provider: "{{ provider }}"
    device_group: "{{ device_group }}"
    name: "{{ created_object_name }}"
    value: "{{ _address }}"
    address_type: "ip-netmask"
    description: "Auto-created address object for {{ _address }}"
    state: present
  register: address_creation

- name: Get existing objects
  paloaltonetworks.panos.panos_address_group:
    provider: "{{ provider }}"
    device_group: "{{ device_group }}"
    name: "{{ _address_group }}"
    state: gathered
  register: existing_group


- name: Add ADDRESS object to preset ADDRESS GROUP
  paloaltonetworks.panos.panos_address_group:
    provider: "{{ provider }}"
    device_group: "{{ device_group }}"
    name: "{{ _address_group }}"
    static_value: "{{ [created_object_name] + existing_group.gathered.static_value }}"
    state: present
  register: group_addition

- name: Display results
  debug:
    msg: |-
      Address object: {{ created_object_name }}
      Added to group: {{ _address_group }}
      Device group: {{ device_group }}
      Status: {{ 'SUCCESS' if group_addition is succeeded else 'FAILED' }}
