---
# This is the Webservers outbound policy. The purpose of these tasks is to take incoming requests and see if they
# match this policy, returning the preset address group that they can be added to when a policy change is required.
# Webservers should be allowed to talk to any host on the internet, so we can disregard the destination IP!

- name: Match Users Internet Policy
  ansible.builtin.set_fact:
    policy_match: true # Set the fact that we did match a policy
    destination_url_category: PRESET_USER_OUTBOUND_URLS # In this case, the policy preset is an address_group type
    device_group: Lab # Finally, we set the device group!
  when:
    - "source_ip is defined or source_user is defined"
    - url is defined
